/* Cytoscape.js application layer; core library is vendored with its license. */
let mapCy=null,detailCy=null;
const cyStyle=[
 {selector:'node',style:{'label':'data(label)','background-color':'#ffffff','border-color':'data(color)','border-width':1.5,'color':'#243f49','font-family':'sans-serif','font-size':13,'text-wrap':'wrap','text-max-width':180,'text-valign':'center','text-halign':'center','width':180,'height':56,'shape':'roundrectangle'}},
 {selector:'node[kind="reaction"]',style:{shape:'roundrectangle','width':110,'height':42,'background-color':'data(color)','color':'white','font-size':11,'text-max-width':105}},
 {selector:'node[kind="species"]',style:{'width':255,'height':96,'font-size':15,'font-weight':'bold'}},
 {selector:'node[kind="annotation"]',style:{'border-width':0,'background-opacity':0,'width':420,'font-size':13,'text-max-width':410,'color':'#5d717b'}},
 {selector:'edge',style:{'curve-style':'bezier','line-color':'#8398a1','target-arrow-color':'#8398a1','target-arrow-shape':'triangle','width':1.6,'label':'data(label)','font-size':11,'text-background-color':'white','text-background-opacity':1,'text-background-padding':3}},
 {selector:'edge[kind="connection"]',style:{'line-style':'dashed','target-arrow-shape':'none','line-color':'#b3c0c5'}},
 {selector:'#roxa_direct',style:{'curve-style':'unbundled-bezier','control-point-distances':-100,'control-point-weights':.5}},
 {selector:':selected',style:{'border-width':3,'border-color':'#162e39'}}
];
function cyNode(id,label,x,y,color,kind='metabolite',extra={}){return {data:{id,label,color,kind,...extra},position:{x,y}}}
function cyEdge(id,source,target,label='',kind='reaction',extra={}){return {data:{id,source,target,label,kind,...extra}}}
const canvas=$('overview').parentNode;const cyHost=document.createElement('div');cyHost.id='cyMap';cyHost.style.cssText='height:650px;width:100%;min-width:700px';canvas.insertBefore(cyHost,$('overview'));$('overview').style.display='none';
const controls=document.createElement('div');controls.style.cssText='display:flex;gap:8px;padding:12px 20px;flex-wrap:wrap';controls.innerHTML='<button id="fitCy">全体に合わせる</button><button id="resetCy">配置を戻す</button><button id="jsonCy">表示中のJSONを保存</button><span class="muted" style="align-self:center">スクロールで拡大・ドラッグで移動</span>';canvas.parentNode.insertBefore(controls,canvas);
function saveBlob(content,type,name){let u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function initMap(elements){if(mapCy)mapCy.destroy();mapCy=cytoscape({container:cyHost,elements,style:cyStyle,layout:{name:'preset',padding:28},minZoom:.2,maxZoom:3,wheelSensitivity:.2});mapCy.on('tap','node',event=>{let d=event.target.data();if(d.pool)showPool(d.pool);else if(d.species&&d.kind==='species'){$('species').value=d.species;$('query').value='';$('kind').value='all';tab('search');renderResults()}else if(d.reaction){tab('search');showReaction(d.species,d.reaction)}else if(d.action==='rubber')$('context').innerHTML='<h2>ゴム分解の動的モデル</h2><p>Lcp/Roxによる切断はdFBAコードに記述された関係です。矢印は実フラックスではありません。</p><p>RoxA/RoxBの異種発現は研究室で未成功。酸素応答はクルードで検証予定です。</p>'})}
initMap([]);
const originalTab=tab;tab=function(which){originalTab(which);if(which==='map'){mapCy.resize();mapCy.fit(undefined,28)}};
const originalPool=showPool;showPool=function(id){originalPool(id);const b=document.createElement('button');b.textContent='交換反応ネットワークを展開';b.style.marginTop='16px';b.onclick=()=>showPoolGraph(id);$('context').appendChild(b)};
function showPoolGraph(id){let nodes=[cyNode('shared',id,470,330,'#587680','metabolite',{pool:id})],edges=[];let rows=[];D.species.forEach(s=>s.reactions.filter(r=>r.pool===id).forEach(r=>rows.push([s,r])));rows.forEach(([s,r],i)=>{let y=80+i*130,n='r'+i;nodes.push(cyNode(n,s.short+'\n'+r.id,220,y,colors[s.short],'reaction',{reaction:r.id,species:s.short,lower:r.bounds[0],upper:r.bounds[1],gpr:r.gpr}));let local='local'+i;nodes.push(cyNode(local,s.short+' GEM\n'+Object.keys(r.stoich)[0],700,y,colors[s.short]));if(r.uptake)edges.push(cyEdge('in'+i,'shared',n,'取込可能'));if(r.secretion)edges.push(cyEdge('out'+i,n,'shared','分泌可能'));edges.push(cyEdge('localedge'+i,n,local,'交換境界','connection'));if(!r.uptake&&!r.secretion)nodes[nodes.length-2].data.label+='\n閉鎖';});initMap([...nodes,...edges]);}
// A single reaction uses the template SVG; no second canvas renderer is needed.
const originalReaction=showReaction;showReaction=function(short,id){if(detailCy){detailCy.destroy();detailCy=null}originalReaction(short,id)};
$('export').textContent='表示図をSVG保存';$('export').onclick=()=>{let bb=mapCy.elements().boundingBox(),pad=30;let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${bb.x1-pad} ${bb.y1-pad} ${bb.w+pad*2} ${bb.h+pad*2}"><defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#8398a1"/></marker></defs><rect x="${bb.x1-pad}" y="${bb.y1-pad}" width="${bb.w+pad*2}" height="${bb.h+pad*2}" fill="white"/>`;mapCy.edges().forEach(e=>{let p=e.sourceEndpoint(),q=e.targetEndpoint(),cp=e.controlPoints(),curve=cp&&cp.length?('Q'+cp[0].x+' '+cp[0].y+' '+q.x+' '+q.y):('L'+q.x+' '+q.y);svg+=`<path d="M${p.x} ${p.y}${curve}" stroke="#8398a1" fill="none" ${e.data('kind')==='connection'?'stroke-dasharray="5 5"':'marker-end="url(#a)"'}/><text x="${(p.x+q.x)/2}" y="${(p.y+q.y)/2-8}" font-size="10" text-anchor="middle">${esc(e.data('label'))}</text>`});mapCy.nodes().forEach(n=>{let p=n.position(),w=n.width(),h=n.height(),d=n.data();if(d.kind!=='annotation')svg+=`<rect x="${p.x-w/2}" y="${p.y-h/2}" width="${w}" height="${h}" rx="8" fill="${d.kind==='reaction'?d.color:'white'}" stroke="${d.color}"/>`;let ls=d.label.split('\n');ls.forEach((l,i)=>svg+=`<text x="${p.x}" y="${p.y+(i-(ls.length-1)/2)*17+5}" font-family="sans-serif" font-size="13" text-anchor="middle" fill="${d.kind==='reaction'?'white':'#243f49'}">${esc(l)}</text>`)});saveBlob(svg+'</svg>','image/svg+xml;charset=utf-8','metabolic_map.svg')};
$('provenance').insertAdjacentHTML('afterbegin','<p><strong>Cytoscape.js '+cytoscape.version+'</strong> · MIT license · ローカル同梱。ノードの移動は表示配置だけを変え、モデルを変更しません。</p>');
showPool('ppa_e');

// Expand the exact stoichiometric neighborhood without inventing pathways.
const cySingleReaction=showReaction;
showReaction=function(short,id){cySingleReaction(short,id);let b=document.createElement('button');b.textContent='周辺反応をネットワーク表示';b.onclick=()=>{let s=D.species.find(s=>s.short===short),seed=s.reactions.find(r=>r.id===id);const currency=new Set(['coa_c','h_c','h_e','h_p','h2o_c','h2o_e','h2o_p','atp_c','adp_c','pi_c','ppi_c','nad_c','nadh_c','nadp_c','nadph_c','cpd00001_c0','cpd00002_c0','cpd00008_c0','cpd00009_c0','cpd00067_c0']);let target=new Set(Object.keys(seed.stoich).filter(m=>!currency.has(m)));let matching=s.reactions.filter(r=>r.id!==id&&Object.keys(r.stoich).some(m=>target.has(m)));let rs=[seed,...matching.slice(0,15)],elements=[],seen=new Set();rs.forEach((r,i)=>{let rid='r'+i;elements.push(cyNode(rid,r.id,i*190,200,colors[short],'reaction',{species:short,reaction:r.id,lower:r.bounds[0],upper:r.bounds[1],gpr:r.gpr}));Object.entries(r.stoich).forEach(([m,c])=>{if(currency.has(m))return;let mid='m'+m;if(!seen.has(mid)){seen.add(mid);elements.push(cyNode(mid,m,seen.size*150,50,colors[short]))}elements.push(cyEdge('e'+i+'_'+m,c<0?mid:rid,c<0?rid:mid,'','reaction',{coefficient:c}))})});tab('map');initMap(elements);mapCy.layout({name:'cose',animate:false,randomize:false,nodeRepulsion:()=>12000,idealEdgeLength:()=>150,padding:30}).run();$('context').innerHTML='<h2>'+esc(short+' · '+id)+'</h2><p>選択反応と、非補酵素プールを共有する隣接反応を表示しています。</p><p>'+rs.length+' 反応 / 隣接候補 '+matching.length+' 件。表示上限は選択反応＋15件。ATP・水・プロトン等の汎用プールは表示を省略しています。完全な反応式は反応ノードを選択して確認してください。</p><p>矢印は化学量論の正方向。可逆性は上下限を参照してください。連結だけで活性経路と断定しません。</p>'};$('detail').prepend(b)};

// Every reaction belongs to exactly one inventory group (used by the Sankey overview and the reaction list filter).
const atlasGroups=new Map();
function atlasGroup(r){if(r.exchange)return '交換・境界';if(r.subsystem&&!/^(exchange|transport)$/i.test(r.subsystem))return '注釈: '+r.subsystem;const t=(r.id+' '+r.name).toLowerCase();for(const [label,re] of [['PHA・貯蔵',/phb_|phv_|ex_pha|ex_phv|polyhydroxy|phac-catalys|phab aceto/],['増殖・維持',/biomass|maintenance|atpm/],['輸送',/transport|symport|antiport|abc system/],['脂質関連',/fatty|lipid|acyl|lipase/],['アミノ酸関連',/amino|alanine|glutamate|arginine|lysine|tryptophan/],['核酸関連',/purine|pyrimidine|nucleotide|adenosine|uridine/],['酸化還元',/dehydrogenase|oxidase|reductase/],['糖・有機酸関連',/glucose|glycol|pyruvate|citrate|lactate|propionat|sugar/]])if(re.test(t))return label;return 'その他・未分類'}
D.species.forEach(s=>{let groups=new Map();s.reactions.forEach(r=>{let g=atlasGroup(r);if(!groups.has(g))groups.set(g,[]);groups.get(g).push(r)});atlasGroups.set(s.short,groups)});

controls.innerHTML='<button id="atlasFit">画面に合わせる</button><button id="atlasMinus">−</button><button id="atlasPlus">＋</button><span id="atlasStatus"></span>';
$('atlasFit').onclick=()=>mapCy.fit(undefined,35);$('atlasPlus').onclick=()=>mapCy.zoom(mapCy.zoom()*1.3);$('atlasMinus').onclick=()=>mapCy.zoom(mapCy.zoom()/1.3);
