/* Escher 1.8.2 is used directly for stoichiometric pathway rendering. */
let escherBuilder=null,escherCurrentMap=null;
const escherHost=document.createElement('div');escherHost.id='escherAtlas';escherHost.style.cssText='display:none;height:65vh;min-height:520px;position:relative;background:white;border:3px solid #426cc0';cyHost.parentNode.append(escherHost);
function makeEscherMap(short,rs){const s=D.species.find(s=>s.short===short),currency=/^(h|h2o|atp|adp|amp|pi|ppi|nad|nadh|nadp|nadph|coa)_[cep]$/;let elements=[],seen=new Set();rs.forEach((r,i)=>{elements.push({data:{id:'r'+i},position:{x:(i%4)*300,y:Math.floor(i/4)*300}});Object.keys(r.stoich).filter(m=>!currency.test(m)).forEach(m=>{if(!seen.has(m)){seen.add(m);elements.push({data:{id:'m'+m},position:{x:seen.size*60,y:100}})}elements.push({data:{id:'e'+i+m,source:'m'+m,target:'r'+i}})})});let layout=cytoscape({headless:true,elements,styleEnabled:false});rs.forEach((r,i)=>layout.getElementById('r'+i).position({x:250+(i%2)*700,y:180+Math.floor(i/2)*500}));for(let m of seen){let pts=[];rs.forEach((r,i)=>{if(m in r.stoich){let p=layout.getElementById('r'+i).position();let ms=Object.keys(r.stoich).filter(x=>!currency.test(x)&&Math.sign(r.stoich[x])===Math.sign(r.stoich[m]));pts.push({x:p.x+(r.stoich[m]<0?-200:200),y:p.y+ms.indexOf(m)*85})}});layout.getElementById('m'+m).position({x:pts.reduce((a,p)=>a+p.x,0)/pts.length,y:pts.reduce((a,p)=>a+p.y,0)/pts.length+(pts.length>1?70:0)});}let nodes={},reactions={},nid=0,sid=0,metNodes={};function node(o){let id=String(nid++);nodes[id]=o;return id}function met(m,p,primary){return node({node_type:'metabolite',x:p.x,y:p.y,bigg_id:m,name:s.metabolites[m].name,label_x:p.x+20,label_y:p.y-15,node_is_primary:primary})}for(let m of seen)metNodes[m]=met(m,layout.getElementById('m'+m).position(),true);
rs.forEach((r,i)=>{let p=layout.getElementById('r'+i).position();let center=node({node_type:'midmarker',x:p.x,y:p.y});let segments={},secondary=0;Object.entries(r.stoich).forEach(([m,c])=>{let mi=metNodes[m];if(mi===undefined)mi=met(m,{x:p.x+(c<0?-100:100),y:p.y+65+secondary++*50},false);let q=nodes[mi],from=c<0?mi:center,to=c<0?center:mi;segments[String(sid++)]={from_node_id:from,to_node_id:to,b1:{x:(p.x+q.x)/2,y:q.y},b2:{x:(p.x+q.x)/2,y:p.y}}});reactions[String(i)]={name:r.name,bigg_id:r.id,reversibility:r.bounds[0]<0&&r.bounds[1]>0,label_x:p.x+12,label_y:p.y-14,gene_reaction_rule:r.gpr,genes:[],metabolites:Object.entries(r.stoich).map(([id,coefficient])=>({bigg_id:id,coefficient})),segments}});layout.destroy();let xs=Object.values(nodes).map(n=>n.x),ys=Object.values(nodes).map(n=>n.y);let x=Math.min(...xs)-100,y=Math.min(...ys)-100,w=Math.max(...xs)-x+200,h=Math.max(...ys)-y+200;return [{map_name:short+' metabolic atlas',map_id:'local-'+short,map_description:'Generated from curated GEM; no flux data; automatic layout',homepage:'https://escher.github.io',schema:'https://escher.github.io/escher/jsonschema/1-0-0#'},{nodes,reactions,text_labels:{'0':{x,y:y-20,text:names[short]+' | '+rs.length+' reactions | static model'}},canvas:{x,y,width:w,height:h}}]}
function escherOpen(short,rs,title){setLayer('escher');escherHost.style.borderColor=colors[short];escherHost.replaceChildren();escherCurrentMap=makeEscherMap(short,rs);escherBuilder=escher.Builder(escherCurrentMap,null,null,escher.libs.d3_select(escherHost),{menu:'zoom',fill_screen:false,enable_editing:false,enable_keys:false,scroll_behavior:'zoom',never_ask_before_quit:true,primary_metabolite_radius:12,secondary_metabolite_radius:6,reaction_no_data_color:'#455c71',metabolite_no_data_color:'#d69273'});document.querySelector('.panelhead h2').textContent=names[short]+' — '+title+' / Escher';$('context').insertAdjacentHTML('afterbegin','<div class="record"><h2>Escher 経路図</h2><p>円：代謝物／線：反応。小さい円は補酵素等。反応名と化学量論は実モデル由来です。表示は自動配置で、手作業で校正した経路地図ではありません。</p><p>この色枠は '+esc(names[short])+' のモデル所属を示します。細胞外区画を含む場合は代謝物IDを参照してください。</p><button id="escherMapSave">Escher JSONを保存</button><button id="escherBack">反応検索に戻る</button></div>');$('escherMapSave').onclick=()=>saveBlob(JSON.stringify(escherCurrentMap,null,2),'application/json',short+'_escher_map.json');$('escherBack').onclick=()=>tab('search');$('atlasStatus').textContent='Escher · '+rs.length+' 反応 · スクロールで拡大';}
const escherReactionBase=showReaction;showReaction=function(short,id){escherReactionBase(short,id);let b=document.createElement('button');b.textContent='Escherで周辺経路を開く';b.onclick=()=>{let s=D.species.find(s=>s.short===short),r=s.reactions.find(r=>r.id===id),skip=/^(h|h2o|atp|adp|amp|pi|ppi|nad|nadh|nadp|nadph|coa)_[cep]$/,m=new Set(Object.keys(r.stoich).filter(x=>!skip.test(x)));let rs=[r,...s.reactions.filter(x=>x.id!==id&&Object.keys(x.stoich).some(k=>m.has(k))).slice(0,11)];tab('map');$('context').innerHTML='<p>選択反応と隣接反応、最大12反応を表示。</p>';escherOpen(short,rs,id)};$('detail').prepend(b)};
const oldFit=$('atlasFit').onclick;$('atlasFit').onclick=()=>{if(AtlasUI.layer==='escher')escherBuilder.map.zoom_extent_canvas();else oldFit()};const oldPlus=$('atlasPlus').onclick,oldMinus=$('atlasMinus').onclick;$('atlasPlus').onclick=()=>AtlasUI.layer==='escher'?escherBuilder.zoom_container.zoom_in():oldPlus();$('atlasMinus').onclick=()=>AtlasUI.layer==='escher'?escherBuilder.zoom_container.zoom_out():oldMinus();
$('provenance').insertAdjacentHTML('afterbegin','<p>経路詳細は <a href="https://escher.github.io/">Escher</a> 1.8.2を使用（MIT、ライセンス同梱）。King et al. (2015), DOI: 10.1371/journal.pcbi.1004321。Cytoscape.jsは中心代謝マップ等に使用。</p>');

const escherSvgBase=$('export').onclick;$('export').onclick=()=>{if(AtlasUI.layer!=='escher'){escherSvgBase();return}let svg=escherHost.querySelector('svg').cloneNode(true);saveBlob(new XMLSerializer().serializeToString(svg),'image/svg+xml','escher_pathway.svg')};// Unified visual language: pathway aggregates, metabolite circles and tinted cells.
const tintedEscherBase=escherOpen;escherOpen=function(short,rs,title){tintedEscherBase(short,rs,title);escherHost.style.background=short==='OR16'?'#eef8f5':short==='NS21'?'#f0f4fc':'#fbf4eb'};

