/* Atlas state, drawing pipeline, asynchronous jobs and portable sessions. */
class FlowSpatialIndex {
  constructor(size=180,padding=20){this.size=size;this.padding=padding;this.cells=new Map()}
  keys(line){const p=this.padding,s=this.size,x=line.map(p=>p.x),y=line.map(p=>p.y),out=[];for(let i=Math.floor((Math.min(...x)-p)/s);i<=Math.floor((Math.max(...x)+p)/s);i++)for(let j=Math.floor((Math.min(...y)-p)/s);j<=Math.floor((Math.max(...y)+p)/s);j++)out.push(i+','+j);return out}
  add(line){for(const key of this.keys(line)){if(!this.cells.has(key))this.cells.set(key,[]);this.cells.get(key).push(line)}}
  near(line){return [...new Set(this.keys(line).flatMap(k=>this.cells.get(k)||[]))]}
}
let flowRendering=false,sessionRestoring=false,sessionTimer=0,calculationScanPending=false,atlasResizeObserver=null;
function flowRender(){
  if(flowRendering||!flowMode||!flowState||!mapCy||flowCanvasSuspended)return;
  flowRendering=true;const renderStart=performance.now();mapCy.startBatch();
  try {
    // State -> required records -> visible graph -> geometry -> appearance.
    branchInit(flowState);
    for(const id of flowState.keep)if(flowState.nodes.get(id)?.data.reaction)ensureRequiredSubstrateRecords(id);
    renderFlowElements();renderPathwayGateways();applyOmissions();styleReactionBackbones();
    splitWaterDisplay();applyOmissions();removeOrphanGateways();styleFlowLabels();
    refineEscherBranches();applyReversibleArrows();applyReactionSelection();applyFbaColors();applyFluxView();bindFoldAnchors();
    appendFlowStyle(mapCy,[{selector:'node[supplyUnverified][fbaSupply="unknown"], node[supplyUnverified][fbaSupply="pending"]',style:{'background-color':'#fff0cc','border-color':'#aa7524','border-style':'dashed','border-width':2}}]).update();
    refreshMediumSummary();scheduleSessionSave();
    if(!calculationScanPending){calculationScanPending=true;queueMicrotask(()=>{calculationScanPending=false;checkVisibleFba()})}
  }finally{mapCy.endBatch();flowRendering=false;if($('atlasStatus'))$('atlasStatus').dataset.renderMs=(performance.now()-renderStart).toFixed(1)}
}

const atlasRequests=new Map();let atlasJobGeneration=0;
async function atlasJSON(url,options={}){const res=await fetch(url,{...options,signal:options.signal||AbortSignal.timeout(20000)});const body=await res.json();if(!res.ok)throw new Error(body.message||'HTTP '+res.status);return body}
function jobStatus(){const box=$('atlasJobStatus');if(!box)return;const all=[...atlasRequests.values()];box.textContent=all.length?'計算中 '+all.filter(x=>x.status==='running').length+'件 · 待ち '+all.filter(x=>x.status!=='running').length+'件':'計算待ちなし';$('cancelAtlasJobs').disabled=!all.length}
function atlasCalculate(kind,body){
  const request={kind,...body},key=JSON.stringify(request);if(atlasRequests.has(key))return atlasRequests.get(key).promise;
  const entry={status:'queued',id:null,generation:atlasJobGeneration};atlasRequests.set(key,entry);
  entry.promise=(async()=>{try{
    const started=await atlasJSON('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)});entry.id=started.id;
    for(;;){
      if(entry.generation!==atlasJobGeneration){await atlasJSON('/api/jobs/'+entry.id+'/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).catch(()=>{});return {status:'cancelled',message:'計算をキャンセルしました'}}
      const job=await atlasJSON('/api/jobs/'+entry.id);if(entry.generation!==atlasJobGeneration)continue;entry.status=job.status;jobStatus();
      if(job.status==='done'||job.status==='failed')return job.result;
      if(job.status==='cancelled')return {status:'cancelled',message:'計算をキャンセルしました'};
      await new Promise(resolve=>setTimeout(resolve,500));
    }
  }catch(error){return {status:'unknown',message:error.message}}finally{if(atlasRequests.get(key)===entry)atlasRequests.delete(key);jobStatus()}})();jobStatus();return entry.promise;
}
function cancelAtlasCalculations(){atlasJobGeneration++;atlasRequests.clear();jobStatus();if(flowState){flowState.calculationEpoch=(flowState.calculationEpoch||0)+1;flowState.fbaPaused=true;flowState.commonRankings?.clear();flowState.fbaResults?.forEach((v,k)=>{if(v.status==='pending')flowState.fbaResults.delete(k)})}const box=$('atlasJobStatus');if(box)box.textContent='待ちを停止しました。実行中の計算は終了後に結果を破棄します。'}
loadCommonRanking=async function(short){const st=flowState,key=short+':'+JSON.stringify(st.mediumOverride||null);st.commonRankings=st.commonRankings||new Map();const cache=st.commonRankings;if(!cache.has(key)){const promise=atlasCalculate('ranking',{species:short,medium:st.mediumOverride||null});cache.set(key,promise);promise.then(value=>{if(value.status!=='optimal'&&cache.get(key)===promise)cache.delete(key)})}return cache.get(key)};

requestReactionFba=async function(st,d){if(!d?.reaction||st.fbaPaused)return;st.fbaResults=st.fbaResults||new Map();const version=JSON.stringify(st.mediumOverride||null),epoch=st.calculationEpoch||0,key=fbaKey(d),r=st.rxnMap.get(d.reaction),sign=d.direction===-1?-1:1;if(st.fbaResults.has(key)||!r||r.exchange)return;const required=Object.entries(r.stoich).filter(([,c])=>c*sign<0).map(([m])=>m);st.fbaResults.set(key,{status:'pending',required});const result=await atlasCalculate('fba',{species:st.s.short,reaction:r.id,sign,medium:st.mediumOverride||null});if(epoch!==(st.calculationEpoch||0)||version!==JSON.stringify(st.mediumOverride||null)||st!==flowState)return;st.fbaResults.set(key,{...result,required});applyFbaColors();applyFluxView();refreshFbaOverlay()};
// Limit visible auto-certificates in flight so foreground pFBA/FVA is not queued behind hundreds of LPs.
checkVisibleFba=function(){if(!flowMode||!flowState||!mapCy||flowCanvasSuspended||sessionRestoring||flowState.fbaPaused)return;const st=flowState;st.fbaResults=st.fbaResults||new Map();const pending=[...st.fbaResults.values()].filter(v=>v.status==='pending').length;const candidates=mapCy.nodes('[kind="fr"]').filter(n=>n.visible()&&!st.fbaResults.has(fbaKey(n.data()))&&!st.rxnMap.get(n.data('reaction'))?.exchange).slice(0,Math.max(0,2-pending));for(const n of candidates)requestReactionFba(st,n.data()).finally(()=>{if(st===flowState&&!st.fbaPaused)setTimeout(checkVisibleFba,0)})};

function refreshMediumSummary(){const box=$('mediumAppliedSummary'),st=flowState;if(!box||!st)return;const medium=st.mediumOverride||D.medium,roots=st.mediumRoots||new Set([st.pool]),ids=[...new Set([...roots,...Object.keys(medium).filter(k=>medium[k]>0)])].sort();if($('flowPool'))for(const option of $('flowPool').options)option.textContent=option.value+' · 適用 '+(medium[option.value]||0)+' mmol/L';box.innerHTML='<summary>適用中の培地 · '+roots.size+'成分を表示 / '+Object.values(medium).filter(v=>v>0).length+'成分に濃度指定 · mmol/L</summary><p>表示起点の適用濃度：'+[...roots].map(id=>esc(id)+' = '+esc(medium[id]||0)).join('、')+'</p><p>画面の起点追加は供給条件を変更しません。水・H⁺は専用の供給規則です。</p><table><thead><tr><th>成分</th><th>表示</th><th>濃度</th></tr></thead><tbody>'+ids.map(id=>'<tr><td>'+esc(id)+'</td><td>'+(roots.has(id)?'表示中':'未表示')+'</td><td>'+esc(medium[id]||0)+(roots.has(id)&&!medium[id]?'（仮想起点）':'')+'</td></tr>').join('')+'</tbody></table>';for(const [id,n] of st.nodes){if(n.data.kind==='feed'){n.data.label=n.data.pool+'\n培地 '+(medium[n.data.pool]||0)+' mmol/L';const node=mapCy.getElementById(id);if(node.length)node.data('label',n.data.label)}}}
function mediumEqual(a,b){return JSON.stringify(Object.entries(a).sort())===JSON.stringify(Object.entries(b).sort())}
editFluxMedium=function(){
 const st=flowState,applied={...(st.mediumOverride||D.medium)},draft={...(st.mediumDraft||applied)},ids=[...new Set([...Object.keys(applied),...Object.keys(draft),...(st.mediumRoots||[st.pool])])].sort();
 const dialog=document.createElement('dialog');dialog.id='fluxMediumEditor';dialog.setAttribute('aria-label','FBA培地条件');dialog.className='atlasDialog';dialog.innerHTML='<h2>培地条件（mmol/L）</h2><p>適用ボタンを押すまで計算条件は変わりません。水・H⁺は専用の供給規則を維持します。</p><button id="onlyShownMedium">表示成分だけ残す</button> <button id="referenceMedium">参照培地</button><div id="fluxMediumRows"></div><p id="mediumDraftStatus" role="status"></p><p id="fluxMediumError" role="alert"></p><button id="applyFluxMedium">適用して再計算</button> <button id="cancelFluxMedium">閉じる</button>';document.body.append(dialog);
 function status(){const dirty=!mediumEqual(draft,applied);st.mediumDraft=dirty?{...draft}:null;$('mediumDraftStatus').textContent=dirty?'未適用の変更があります':'適用中の条件と同じです';$('mediumPending').textContent=dirty?'未適用の培地変更あり':'';scheduleSessionSave()}
 function rows(){$('fluxMediumRows').innerHTML=ids.map(id=>'<label class="mediumRow"><span>'+esc(id)+'</span><input aria-label="'+esc(id)+' 濃度" data-medium="'+esc(id)+'" type="number" min="0" step="any" value="'+(draft[id]||0)+'" '+(['h2o_e','h_e'].includes(id)?'disabled':'')+'></label>').join('');dialog.querySelectorAll('[data-medium]').forEach(input=>input.oninput=()=>{const n=input.valueAsNumber;if(Number.isFinite(n)&&n>=0){draft[input.dataset.medium]=n;status()}else $('mediumDraftStatus').textContent='濃度を0以上の数値で入力してください。'});status()}
 $('onlyShownMedium').onclick=()=>{for(const id of ids)if(!(st.mediumRoots||new Set([st.pool])).has(id)&&!['h2o_e','h_e'].includes(id))draft[id]=0;rows()};$('referenceMedium').onclick=()=>{for(const id of ids)draft[id]=D.medium[id]||0;rows()};
 const close=()=>{dialog.close();dialog.remove()};$('cancelFluxMedium').onclick=close;dialog.addEventListener('cancel',()=>dialog.remove());
 $('applyFluxMedium').onclick=()=>{for(const input of dialog.querySelectorAll('[data-medium]'))if(input.value===''||!Number.isFinite(input.valueAsNumber)||input.valueAsNumber<0){$('fluxMediumError').textContent='濃度を0以上の数値で入力してください。';return}if(st!==flowState){close();return}cancelAtlasCalculations();st.fbaPaused=false;st.mediumOverride={...draft};st.mediumDraft=null;st.fbaResults=new Map();st.commonRankings=new Map();st.fluxResult=null;st.fluxEnabled=true;$('fluxEnabled').checked=true;$('mediumPending').textContent='';close();refreshMediumSummary();scheduleSessionSave();calculateFlux();checkVisibleFba()};rows();dialog.showModal();
};

function fvaLabel(state){return {forward:'順方向に固定',reverse:'逆方向に固定',both:'順・逆の両方向が可能',forward_or_zero:'順方向またはゼロ',reverse_or_zero:'逆方向またはゼロ',zero:'ゼロ流量に固定'}[state]||'未確定'}
const detailedReactionOverlay=openReactionOverlay;
openReactionOverlay=function(data){detailedReactionOverlay(data);const st=flowState,version=JSON.stringify(st.mediumOverride||null),box=document.createElement('section');box.innerHTML='<h3>最適解間の方向の安定性</h3><button id="runReactionFva">この反応をFVAで確認</button><p id="reactionFvaResult" role="status">共通pFBAは一つの解です。ゼロや逆方向が必然とは限りません。</p>';reactionOverlay.append(box);box.querySelector('button').onclick=async()=>{box.querySelector('button').disabled=true;box.querySelector('p').textContent='FVAを計算中…';const result=await atlasCalculate('fva',{species:st.s.short,reaction:data.reaction,medium:st.mediumOverride||null});if(st!==flowState||version!==JSON.stringify(st.mediumOverride||null)||!box.isConnected)return;box.querySelector('button').disabled=false;box.querySelector('p').textContent=result.status==='optimal'?fvaLabel(result.direction_stability)+'：'+result.minimum.toPrecision(5)+' ～ '+result.maximum.toPrecision(5)+' mmol/gDW/h。元の目的値を維持（循環除去制約なし）。':result.message}};

function openCompoundPanel(node){
 const st=flowState,id=node.id(),d=node.data(),m=st.s.metabolites[d.mid];if(!m)return;hideCompoundTools();
 const dialog=document.createElement('dialog');dialog.id='compoundPanel';dialog.className='atlasDialog';dialog.setAttribute('aria-label','化合物の詳細');dialog.innerHTML='<button class="close" style="float:right">閉じる</button><h2>'+esc(d.mid)+'</h2><p>'+esc(m.name)+'</p><p>'+esc(m.formula||'組成式未登録')+'</p><div class="compoundStructure">構造を取得中…</div><button data-side="before">前を省略／再表示</button> <button data-side="after">後を省略／再表示</button> <button class="candidates">候補反応を選ぶ</button>';document.body.append(dialog);const close=()=>{dialog.close();dialog.remove()};dialog.querySelector('.close').onclick=close;dialog.addEventListener('cancel',()=>dialog.remove());dialog.querySelectorAll('[data-side]').forEach(b=>{const update=()=>b.textContent=(b.dataset.side==='before'?'前':'後')+(st.omissionGroups?.has(id+':'+b.dataset.side)?'を再表示':'を省略');update();b.onclick=()=>{omitDirection(id,b.dataset.side);update()}});dialog.querySelector('.candidates').onclick=()=>{close();showReactionChooser(id)};dialog.showModal();const key=st.s.short+':'+d.mid;const pending=structureCache.get(key)||atlasJSON('/api/structure?species='+encodeURIComponent(st.s.short)+'&met='+encodeURIComponent(d.mid));Promise.resolve(pending).then(result=>{if(!dialog.isConnected)return;const area=dialog.querySelector('.compoundStructure');if(result.status==='ok'){structureCache.set(key,result);area.innerHTML=result.svg;const svg=area.querySelector('svg');svg.setAttribute('viewBox',svg.getAttribute('viewBox')||'0 0 320 220');svg.setAttribute('preserveAspectRatio','xMidYMid meet')}else area.textContent=result.message}).catch(()=>{if(dialog.isConnected)dialog.querySelector('.compoundStructure').textContent='構造を取得できませんでした'});
}

const snapshotSets=['keep','keepEdges','expanded','visibleProducts','layoutDone','hiddenReactions','hiddenNodes','mediumRoots'];
const snapshotMaps=['omissionGroups','majorShown','majorPending','gatewayPositions','waterPositions'];
function packAtlasSession(){const st=flowState;const ids=new Set([...st.keep,...mapCy.nodes().map(n=>n.id())]);const view={species:st.s.short,pool:st.pool,selected:st.selected,mediumOverride:st.mediumOverride||null,mediumDraft:st.mediumDraft||null,fluxEnabled:!!st.fluxEnabled,fluxAnimate:!!st.fluxAnimate,autoMajorEnabled,zoom:mapCy.zoom(),pan:mapCy.pan(),nodes:[...ids].filter(id=>st.nodes.has(id)).map(id=>{const n=st.nodes.get(id),cy=mapCy.getElementById(id);return {data:{...n.data},position:cy.length?{...cy.position()}:n.position}}),edges:st.edges.filter(e=>!e.data.id.startsWith('fedge_'))};for(const key of snapshotSets)view[key]=[...(st[key]||(key==='mediumRoots'?[st.pool]:[]))];for(const key of snapshotMaps)view[key]=[...(st[key]||[])].map(([k,v])=>[k,key==='omissionGroups'?[...v]:v]);return {schema:1,model:D.model_fingerprint,savedAt:new Date().toISOString(),view}}
function validateAtlasSession(payload){
 if(!payload||payload.schema!==1||payload.model!==D.model_fingerprint)throw new Error('保存時と現在のモデルが異なるか、保存形式が不正です。');
 const v=payload.view,s=D.species.find(s=>s.short===v?.species);if(!s||!s.reactions.some(r=>r.pool===v.pool))throw new Error('菌種または培地起点が不正です。');
 if(!Array.isArray(v.nodes)||v.nodes.length>12000||!Array.isArray(v.edges)||v.edges.length>20000)throw new Error('表示データが不正です。');
 const reactions=new Set(s.reactions.map(r=>r.id));for(const n of v.nodes){if(!n.data||typeof n.data.id!=='string'||(n.data.reaction&&!reactions.has(n.data.reaction))||(n.data.mid&&!s.metabolites[n.data.mid])||!Number.isFinite(n.position?.x)||!Number.isFinite(n.position?.y))throw new Error('ノードまたは座標が不正です。')}
 const allowed=new Set([...Object.keys(D.medium),...D.species.flatMap(s=>s.reactions.map(r=>r.pool).filter(Boolean))]);for(const medium of [v.mediumOverride,v.mediumDraft])if(medium&&(typeof medium!=='object'||Array.isArray(medium)||Object.entries(medium).some(([k,n])=>!allowed.has(k)||typeof n!=='number'||!Number.isFinite(n)||n<0)))throw new Error('培地条件が不正です。');
 for(const key of snapshotSets)if(!Array.isArray(v[key])||v[key].some(x=>typeof x!=='string'))throw new Error('選択状態が不正です。');for(const key of snapshotMaps)if(!Array.isArray(v[key])||v[key].some(x=>!Array.isArray(x)||x.length!==2||typeof x[0]!=='string'))throw new Error('配置状態が不正です。');
 const nodeIds=new Set(['feed',...Object.keys(s.metabolites).map(m=>'m_'+m),...s.reactions.flatMap(r=>r.exchange?['ex_'+r.id]:['r_'+r.id+'_1','r_'+r.id+'_-1']),...v.nodes.map(n=>n.data.id)]);
 for(const e of v.edges)if(!e?.data||typeof e.data.id!=='string'||!nodeIds.has(e.data.source)||!nodeIds.has(e.data.target))throw new Error('接続先が不正です。');
 for(const key of ['gatewayPositions','waterPositions'])for(const [,p] of v[key])if(!Number.isFinite(p?.x)||!Number.isFinite(p?.y))throw new Error('補助ノードの座標が不正です。');
 for(const [,group] of v.omissionGroups)if(!Array.isArray(group)||group.some(id=>typeof id!=='string'))throw new Error('省略状態が不正です。');
 for(const [key,info] of v.majorShown)if(!majorPathways.some(p=>p.id===key)||!info?.pathway||!Array.isArray(info.added)||!Array.isArray(info.addedEdges)||!Array.isArray(info.pathway.reactions))throw new Error('経路の保存状態が不正です。');
 for(const [key,info] of v.majorPending)if(!majorPathways.some(p=>p.id===key)||!info?.pathway||typeof info.entrance!=='string'||typeof info.trigger!=='string')throw new Error('経路入口の保存状態が不正です。');
 if(v.coreMode!==undefined&&v.coreMode!==1)throw new Error('中心代謝モードが不正です。');
 if(v.coreMode===1&&(!Array.isArray(v.coreConnections)||v.coreConnections.length>400||v.coreConnections.some(x=>!x||typeof x.pool!=='string'||typeof x.reason!=='string'||typeof x.status!=='string'||(x.target&&!s.metabolites[x.target])||(x.reactions&&(!Array.isArray(x.reactions)||x.reactions.some(id=>!reactions.has(id)))))))throw new Error('栄養接続の保存状態が不正です。');
 if(!Number.isFinite(v.zoom)||v.zoom<.15||v.zoom>3||!Number.isFinite(v.pan?.x)||!Number.isFinite(v.pan?.y))throw new Error('画面位置が不正です。');return v;
}
async function restoreAtlasSession(payload){const v=validateAtlasSession(payload);cancelAtlasCalculations();sessionRestoring=true;try{openFlow(v.species,v.pool);const st=flowState,fresh=flowIndex(v.species,v.pool);st.coreMode=v.coreMode===1;st.coreAuxVisible=!!v.coreAuxVisible;st.coreConnections=v.coreConnections||[];for(const key of ['nodes','edges','out','incoming','dist','parent','root','queue','layers','rxnMap'])st[key]=fresh[key];for(const n of v.nodes)st.nodes.set(n.data.id,structuredClone(n));for(const e of v.edges){if(!st.nodes.has(e.data.source)||!st.nodes.has(e.data.target))throw new Error('接続先が不正です。');if(!st.edges.some(x=>x.data.id===e.data.id)){st.edges.push(structuredClone(e));if(!st.out.has(e.data.source))st.out.set(e.data.source,[]);st.out.get(e.data.source).push(e);if(!st.incoming.has(e.data.target))st.incoming.set(e.data.target,[]);st.incoming.get(e.data.target).push(e)}}for(const key of snapshotSets)st[key]=new Set(v[key]);if(!st.coreMode)st.mediumRoots.add(st.pool);const roots=[...st.mediumRoots].map(pool=>!st.coreMode&&pool===st.pool?'feed':'feed_'+pool);st.dist=new Map(roots.map(id=>[id,0]));st.parent=new Map();st.queue=[...roots];for(let i=0;i<st.queue.length;i++){const id=st.queue[i];for(const e of st.out.get(id)||[]){const target=e.data.target;if(!st.dist.has(target)){st.dist.set(target,st.dist.get(id)+1);st.parent.set(target,{id,edge:e.data.id});st.queue.push(target)}}}for(const key of snapshotMaps)st[key]=new Map(v[key].map(([k,val])=>[k,key==='omissionGroups'?new Set(val):val]));st.selected=v.selected;st.mediumOverride=v.mediumOverride;st.mediumDraft=v.mediumDraft;st.fluxEnabled=v.fluxEnabled;st.fluxAnimate=v.fluxAnimate;st.fbaPaused=false;autoMajorEnabled=v.autoMajorEnabled;$('autoMajorToggle').checked=autoMajorEnabled;mapCy.elements().remove();flowRender();mapCy.batch(()=>{for(const n of v.nodes){const cy=mapCy.getElementById(n.data.id);if(cy.length)cy.position(n.position)}mapCy.zoom(v.zoom);mapCy.pan(v.pan)});$('fluxEnabled').checked=st.fluxEnabled;$('fluxAnimate').checked=st.fluxAnimate;$('mediumPending').textContent=st.mediumDraft?'未適用の培地変更あり':'';refineEscherBranches();refreshMediumSummary();$('sessionStatus').textContent='保存した表示・配置・培地を復元しました。計算結果は再計算します。'}finally{sessionRestoring=false}const pageUrl=new URL(location.href);pageUrl.searchParams.delete('session');history.replaceState(null,'',pageUrl);scheduleSessionSave();if(flowState.fluxEnabled)calculateFlux();checkVisibleFba()}
function scheduleSessionSave(){if(sessionRestoring||!flowMode||!flowState||!D.model_fingerprint)return;clearTimeout(sessionTimer);sessionTimer=setTimeout(()=>{try{localStorage.setItem('metabolic-atlas-session',JSON.stringify(packAtlasSession()));if($('sessionAutoStatus'))$('sessionAutoStatus').textContent='この端末に自動保存済み'}catch{if($('sessionAutoStatus'))$('sessionAutoStatus').textContent='自動保存できません。JSON書き出しを利用してください。'}},650)}
function sessionError(error){$('sessionStatus').textContent=error.message||String(error)}
function installAtlasControls(){
 if(!flowMode||!flowState||$('atlasSessionControls'))return;const st=flowState,box=document.createElement('section');box.id='atlasSessionControls';box.innerHTML='<h3>表示状態の保存</h3><button id="saveServerSession">サーバーに保存</button> <button id="loadServerSession">保存一覧</button> <button id="exportSession">JSON書き出し</button> <button id="importSession">JSON読込み</button><input id="sessionFile" type="file" accept="application/json,.json" hidden><p id="sessionStatus" role="status"></p><small id="sessionAutoStatus"></small><h3>計算待ち</h3><p id="atlasJobStatus" role="status">計算待ちなし</p><button id="cancelAtlasJobs">計算待ちを停止</button> <button id="retryAtlasJobs">判定を再開</button><p id="mediumPending" role="status"></p><details id="mediumAppliedSummary"></details>';$('context').prepend(box);
 $('cancelAtlasJobs').onclick=cancelAtlasCalculations;$('retryAtlasJobs').onclick=()=>{st.fbaPaused=false;st.fbaResults?.forEach((v,k)=>{if(!['feasible','infeasible'].includes(v.status))st.fbaResults.delete(k)});checkVisibleFba()};
 $('exportSession').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(packAtlasSession(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='metabolic-atlas-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 $('importSession').onclick=()=>$('sessionFile').click();$('sessionFile').onchange=async e=>{try{const file=e.target.files[0];if(!file||file.size>2000000)throw new Error('2 MB以下の保存JSONを選択してください。');await restoreAtlasSession(JSON.parse(await file.text()))}catch(error){sessionError(error)}};
 $('saveServerSession').onclick=async()=>{try{const result=await atlasJSON('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(packAtlasSession())});const url=new URL(location.href);url.searchParams.set('session',result.id);$('sessionStatus').innerHTML='保存しました。同じサーバーへ接続した別端末で、保存一覧から開けます。<br><a href="'+esc(url.href)+'">この保存状態のリンク</a>'}catch(error){sessionError(error)}};
 $('loadServerSession').onclick=async()=>{try{const result=await atlasJSON('/api/sessions');const dialog=document.createElement('dialog');dialog.className='atlasDialog';dialog.innerHTML='<h2>サーバーの保存状態</h2><button class="close">閉じる</button><div>'+result.sessions.map(x=>'<p><button data-session="'+esc(x.id)+'">'+esc(new Date(x.saved_at*1000).toLocaleString())+' を復元</button></p>').join('')+(result.sessions.length?'':'<p>保存状態はありません。</p>')+'</div>';document.body.append(dialog);dialog.querySelector('.close').onclick=()=>dialog.remove();dialog.querySelectorAll('[data-session]').forEach(b=>b.onclick=async()=>{try{const payload=await atlasJSON('/api/sessions/'+b.dataset.session);await restoreAtlasSession(payload);dialog.remove()}catch(error){sessionError(error);dialog.remove()}});dialog.showModal()}catch(error){sessionError(error)}};
 const legend=document.createElement('p');legend.id='fbaEvidenceLegend';legend.textContent='反応線：青＝共通pFBAで流れる、紫の破線＝共通解はゼロ・個別の成立解あり、灰＝共通解ゼロ、点線＝未計算。別解の流量はアニメーションに使いません。';$('fluxControls').append(legend);
 const speed=document.createElement('p');speed.id='fluxRouteStatus';$('fluxControls').append(speed);const condition=document.createElement('p');condition.id='fluxConditionSummary';condition.textContent=names[st.s.short]+' · 単一細胞・定常 · GEM目的関数 → 総絶対流量最小化 · 在庫換算 0.025 h / 菌体 0.21 gDW/L';$('fluxControls').append(condition);
 const cy=mapCy;cy.on('pan zoom dragfree',scheduleSessionSave);cy.on('tap','node',()=>scheduleSessionSave());
 cy.off('tap');cy.on('tap','node',e=>{const d=e.target.data();if(d.reaction)openReactionOverlay(d);else if(d.mid&&matchMedia('(pointer: coarse), (max-width: 850px)').matches)openCompoundPanel(e.target);else flowChoose(d.id)});
 // An explicit detail action is also available to keyboard/mouse users.
 cy.on('cxttap','node',e=>{if(e.target.data('mid'))openCompoundPanel(e.target)});
 refreshMediumSummary();jobStatus();
}
const atlasFitOriginal=$('atlasFit').onclick;
$('atlasFit').onclick=()=>{if(!flowMode){atlasFitOriginal();return}mapCy.resize();mapCy.fit(mapCy.elements().filter(e=>e.visible()),32);scheduleSessionSave()};
const atlasOpenBase=openFlow;
openFlow=function(...args){if(flowState&&!sessionRestoring)cancelAtlasCalculations();atlasOpenBase(...args);atlasResizeObserver?.disconnect();const cy=mapCy;atlasResizeObserver=new ResizeObserver(()=>{if(cy===mapCy&&!cy.destroyed()){cy.resize();fluxDirty=true}});atlasResizeObserver.observe(cyHost);installAtlasControls();refreshMediumSummary();scheduleSessionSave()};

async function startAtlas(){let saved=null;try{saved=localStorage.getItem('metabolic-atlas-session')}catch{}sessionRestoring=true;try{openFlow()}finally{sessionRestoring=false}const session=new URLSearchParams(location.search).get('session');try{if(session)await restoreAtlasSession(await atlasJSON('/api/sessions/'+encodeURIComponent(session)));else if(saved)await restoreAtlasSession(JSON.parse(saved));else{scheduleSessionSave();checkVisibleFba()}}catch(error){clearTimeout(sessionTimer);sessionError(error)}}
