/* Cytoscape.js application layer; core library is vendored with its license. */
let mapCy=null,detailCy=null;
const cyStyle=[
 {selector:'node',style:{'label':'data(label)','background-color':'#ffffff','border-color':'data(color)','border-width':1.5,'color':'#243f49','font-family':'sans-serif','font-size':13,'text-wrap':'wrap','text-max-width':180,'text-valign':'center','text-halign':'center','width':180,'height':56,'shape':'roundrectangle'}},
 {selector:'node[kind="reaction"]',style:{shape:'roundrectangle','width':110,'height':42,'background-color':'data(color)','color':'white','font-size':11,'text-max-width':105}},
 {selector:'node[kind="species"]',style:{'width':255,'height':96,'font-size':15,'font-weight':'bold'}},
 {selector:'node[kind="annotation"]',style:{'border-width':0,'background-opacity':0,'width':420,'font-size':13,'text-max-width':410,'color':'#5d717b'}},
 {selector:'edge',style:{'curve-style':'bezier','line-color':'#8398a1','target-arrow-color':'#8398a1','target-arrow-shape':'triangle','width':1.6,'label':'data(label)','font-size':11,'text-background-color':'white','text-background-opacity':1,'text-background-padding':3}},
 {selector:'edge[kind="connection"]',style:{'line-style':'dashed','target-arrow-shape':'none','line-color':'#b3c0c5'}},
 {selector:'#roxa_direct',style:{'curve-style':'unbundled-bezier','control-point-distances':-100,'control-point-weights':.5}},
 {selector:':selected',style:{'border-width':3,'border-color':'#162e39'}}
];
function cyNode(id,label,x,y,color,kind='metabolite',extra={}){return {data:{id,label,color,kind,...extra},position:{x,y}}}
function cyEdge(id,source,target,label='',kind='reaction',extra={}){return {data:{id,source,target,label,kind,...extra}}}
function overviewElements(){let a=[cyNode('rubber','天然ゴム\nbulk rubber',130,80,'#627f8a','metabolite',{action:'rubber'}),cyNode('c30','C30オリゴマー',475,80,'#627f8a','metabolite',{pool:'C30_oligo_e'}),cyNode('odtd','ODTD',825,80,'#627f8a','metabolite',{pool:'odtd_e'}),
 cyEdge('lcp_roxb','rubber','c30','Lcp / RoxB · dFBA'),cyEdge('roxa_oligo','c30','odtd','RoxA · dFBA'),cyEdge('roxa_direct','rubber','odtd','RoxA 直接切断 · dFBA'),
 cyNode('dynnote','細胞外の動的切断 · O₂消費を伴うモデル反応',475,175,'#aaa','annotation'),cyNode('poolnote','共有培地 · ノードを選択して交換境界を確認',475,235,'#aaa','annotation')];
 pools.forEach(([id,label],i)=>a.push(cyNode('pool_'+id,label+'\n'+id,100+(i%5)*190,300+Math.floor(i/5)*95,'#9aafb7','metabolite',{pool:id})));
 D.species.forEach((s,i)=>{let id='species_'+s.short;a.push(cyNode(id,s.short+'\n'+s.reactions.length+' 反応 · '+Object.keys(s.metabolites).length+' 代謝物',165+i*310,565,colors[s.short],'species',{species:s.short}));a.push(cyEdge('conn_'+s.short,id,'pool_'+['lac__L_e','o2_e','ppa_e'][i],'共有プール接続','connection'))});
 a.push(cyNode('modelnote','破線は接続の概略。菌種の全交換境界はプール選択から参照。',475,660,'#aaa','annotation'));
 return a;
}
const canvas=$('overview').parentNode;const cyHost=document.createElement('div');cyHost.id='cyMap';cyHost.style.cssText='height:650px;width:100%;min-width:700px';canvas.insertBefore(cyHost,$('overview'));$('overview').style.display='none';
const controls=document.createElement('div');controls.style.cssText='display:flex;gap:8px;padding:12px 20px;flex-wrap:wrap';controls.innerHTML='<button id="fitCy">全体に合わせる</button><button id="resetCy">配置を戻す</button><button id="jsonCy">表示中のJSONを保存</button><span class="muted" style="align-self:center">スクロールで拡大・ドラッグで移動</span>';canvas.parentNode.insertBefore(controls,canvas);
function saveBlob(content,type,name){let u=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function initMap(elements){if(mapCy)mapCy.destroy();mapCy=cytoscape({container:cyHost,elements,style:cyStyle,layout:{name:'preset',padding:28},minZoom:.2,maxZoom:3,wheelSensitivity:.2});mapCy.on('tap','node',event=>{let d=event.target.data();if(d.pool)showPool(d.pool);else if(d.species&&d.kind==='species'){$('species').value=d.species;$('query').value='';$('kind').value='all';tab('search');renderResults()}else if(d.reaction){tab('search');showReaction(d.species,d.reaction)}else if(d.action==='rubber')$('context').innerHTML='<h2>ゴム分解の動的モデル</h2><p>Lcp/Roxによる切断はdFBAコードに記述された関係です。矢印は実フラックスではありません。</p><p>RoxA/RoxBの異種発現は研究室で未成功。酸素応答はクルードで検証予定です。</p>'})}
initMap(overviewElements());$('fitCy').onclick=()=>mapCy.fit(undefined,28);$('resetCy').onclick=()=>initMap(overviewElements());$('jsonCy').onclick=()=>saveBlob(JSON.stringify(mapCy.json(),null,2),'application/json','visible_network.cyjs');
const originalTab=tab;tab=function(which){originalTab(which);if(which==='map'){mapCy.resize();mapCy.fit(undefined,28)}};
const originalPool=showPool;showPool=function(id){originalPool(id);const b=document.createElement('button');b.textContent='交換反応ネットワークを展開';b.style.marginTop='16px';b.onclick=()=>showPoolGraph(id);$('context').appendChild(b)};
function showPoolGraph(id){let nodes=[cyNode('shared',id,470,330,'#587680','metabolite',{pool:id})],edges=[];let rows=[];D.species.forEach(s=>s.reactions.filter(r=>r.pool===id).forEach(r=>rows.push([s,r])));rows.forEach(([s,r],i)=>{let y=80+i*130,n='r'+i;nodes.push(cyNode(n,s.short+'\n'+r.id,220,y,colors[s.short],'reaction',{reaction:r.id,species:s.short,lower:r.bounds[0],upper:r.bounds[1],gpr:r.gpr}));let local='local'+i;nodes.push(cyNode(local,s.short+' GEM\n'+Object.keys(r.stoich)[0],700,y,colors[s.short]));if(r.uptake)edges.push(cyEdge('in'+i,'shared',n,'取込可能'));if(r.secretion)edges.push(cyEdge('out'+i,n,'shared','分泌可能'));edges.push(cyEdge('localedge'+i,n,local,'交換境界','connection'));if(!r.uptake&&!r.secretion)nodes[nodes.length-2].data.label+='\n閉鎖';});initMap([...nodes,...edges]);}
// A single reaction uses the template SVG; no second canvas renderer is needed.
const originalReaction=showReaction;showReaction=function(short,id){if(detailCy){detailCy.destroy();detailCy=null}originalReaction(short,id)};
$('export').textContent='表示図をSVG保存';$('export').onclick=()=>{let bb=mapCy.elements().boundingBox(),pad=30;let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${bb.x1-pad} ${bb.y1-pad} ${bb.w+pad*2} ${bb.h+pad*2}"><defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#8398a1"/></marker></defs><rect x="${bb.x1-pad}" y="${bb.y1-pad}" width="${bb.w+pad*2}" height="${bb.h+pad*2}" fill="white"/>`;mapCy.edges().forEach(e=>{let p=e.sourceEndpoint(),q=e.targetEndpoint(),cp=e.controlPoints(),curve=cp&&cp.length?('Q'+cp[0].x+' '+cp[0].y+' '+q.x+' '+q.y):('L'+q.x+' '+q.y);svg+=`<path d="M${p.x} ${p.y}${curve}" stroke="#8398a1" fill="none" ${e.data('kind')==='connection'?'stroke-dasharray="5 5"':'marker-end="url(#a)"'}/><text x="${(p.x+q.x)/2}" y="${(p.y+q.y)/2-8}" font-size="10" text-anchor="middle">${esc(e.data('label'))}</text>`});mapCy.nodes().forEach(n=>{let p=n.position(),w=n.width(),h=n.height(),d=n.data();if(d.kind!=='annotation')svg+=`<rect x="${p.x-w/2}" y="${p.y-h/2}" width="${w}" height="${h}" rx="8" fill="${d.kind==='reaction'?d.color:'white'}" stroke="${d.color}"/>`;let ls=d.label.split('\n');ls.forEach((l,i)=>svg+=`<text x="${p.x}" y="${p.y+(i-(ls.length-1)/2)*17+5}" font-family="sans-serif" font-size="13" text-anchor="middle" fill="${d.kind==='reaction'?'white':'#243f49'}">${esc(l)}</text>`)});saveBlob(svg+'</svg>','image/svg+xml;charset=utf-8','metabolic_map.svg')};
$('provenance').insertAdjacentHTML('afterbegin','<p><strong>Cytoscape.js '+cytoscape.version+'</strong> · MIT license · ローカル同梱。ノードの移動は表示配置だけを変え、モデルを変更しません。</p>');
showPool('ppa_e');

// Expand the exact stoichiometric neighborhood without inventing pathways.
const cySingleReaction=showReaction;
showReaction=function(short,id){cySingleReaction(short,id);let b=document.createElement('button');b.textContent='周辺反応をネットワーク表示';b.onclick=()=>{let s=D.species.find(s=>s.short===short),seed=s.reactions.find(r=>r.id===id);const currency=new Set(['coa_c','h_c','h_e','h_p','h2o_c','h2o_e','h2o_p','atp_c','adp_c','pi_c','ppi_c','nad_c','nadh_c','nadp_c','nadph_c','cpd00001_c0','cpd00002_c0','cpd00008_c0','cpd00009_c0','cpd00067_c0']);let target=new Set(Object.keys(seed.stoich).filter(m=>!currency.has(m)));let matching=s.reactions.filter(r=>r.id!==id&&Object.keys(r.stoich).some(m=>target.has(m)));let rs=[seed,...matching.slice(0,15)],elements=[],seen=new Set();rs.forEach((r,i)=>{let rid='r'+i;elements.push(cyNode(rid,r.id,i*190,200,colors[short],'reaction',{species:short,reaction:r.id,lower:r.bounds[0],upper:r.bounds[1],gpr:r.gpr}));Object.entries(r.stoich).forEach(([m,c])=>{if(currency.has(m))return;let mid='m'+m;if(!seen.has(mid)){seen.add(mid);elements.push(cyNode(mid,m,seen.size*150,50,colors[short]))}elements.push(cyEdge('e'+i+'_'+m,c<0?mid:rid,c<0?rid:mid,'','reaction',{coefficient:c}))})});tab('map');initMap(elements);mapCy.layout({name:'cose',animate:false,randomize:false,nodeRepulsion:()=>12000,idealEdgeLength:()=>150,padding:30}).run();$('context').innerHTML='<h2>'+esc(short+' · '+id)+'</h2><p>選択反応と、非補酵素プールを共有する隣接反応を表示しています。</p><p>'+rs.length+' 反応 / 隣接候補 '+matching.length+' 件。表示上限は選択反応＋15件。ATP・水・プロトン等の汎用プールは表示を省略しています。完全な反応式は反応ノードを選択して確認してください。</p><p>矢印は化学量論の正方向。可逆性は上下限を参照してください。連結だけで活性経路と断定しません。</p>'};$('detail').prepend(b)};

// Hierarchical atlas: every reaction belongs to exactly one visible inventory group.
const atlasGroups=new Map();
function atlasGroup(r){if(r.exchange)return '交換・境界';if(r.subsystem&&!/^(exchange|transport)$/i.test(r.subsystem))return '注釈: '+r.subsystem;const t=(r.id+' '+r.name).toLowerCase();for(const [label,re] of [['PHA・貯蔵',/phb_|phv_|ex_pha|ex_phv|polyhydroxy|phac-catalys|phab aceto/],['増殖・維持',/biomass|maintenance|atpm/],['輸送',/transport|symport|antiport|abc system/],['脂質関連',/fatty|lipid|acyl|lipase/],['アミノ酸関連',/amino|alanine|glutamate|arginine|lysine|tryptophan/],['核酸関連',/purine|pyrimidine|nucleotide|adenosine|uridine/],['酸化還元',/dehydrogenase|oxidase|reductase/],['糖・有機酸関連',/glucose|glycol|pyruvate|citrate|lactate|propionat|sugar/]])if(re.test(t))return label;return 'その他・未分類'}
D.species.forEach(s=>{let groups=new Map();s.reactions.forEach(r=>{let g=atlasGroup(r);if(!groups.has(g))groups.set(g,[]);groups.get(g).push(r)});atlasGroups.set(s.short,groups)});
let atlasFocus="NS21"; let atlasLevel=0,atlasSelected=null,atlasPage=0,atlasAuto=true,atlasBusy=false;
const atlasCSS=document.createElement('style');atlasCSS.textContent='#mappane{grid-template-columns:minmax(0,1fr) 280px}.canvas{padding:0;overflow:hidden}#cyMap{min-width:0!important;height:calc(100vh - 270px)!important;min-height:470px}header{padding:14px 24px}header h1{font-size:23px}.toolbar{padding:10px 24px}#atlasStatus{font-size:12px} @media(max-width:850px){#mappane{grid-template-columns:1fr}#cyMap{height:65vh!important}}';document.head.append(atlasCSS);
controls.innerHTML='<button id="atlasHome">3細胞の全体</button><button id="atlasGroups">分類を展開</button><button id="atlasBack">1段折りたたむ</button><button id="atlasFit">画面に合わせる</button><button id="atlasMinus">−</button><button id="atlasPlus">＋</button><label><input type="checkbox" id="atlasAuto" checked style="min-width:0">ズームで階層切替</label><span id="atlasStatus"></span>';
cyStyle.push({selector:'node[kind="cell"]',style:{'shape':'roundrectangle','background-color':'data(color)','background-opacity':.06,'border-color':'data(color)','border-width':3,'padding':35,'text-valign':'top','text-margin-y':-12,'font-size':19,'font-weight':'bold'}},{selector:'node[kind="group"]',style:{'width':210,'height':64,'font-size':14}},{selector:'node[kind="summary"]',style:{'width':250,'height':180,'font-size':20,'text-max-width':235}},{selector:'edge[kind="mapping"]',style:{'line-style':'dashed','target-arrow-shape':'none','opacity':.45}});
function atlasDraw(level,selection=null,page=0){atlasBusy=true;atlasLevel=level;atlasSelected=selection;atlasPage=page;let elements=[];let active=level===2&&selection;let chosen=active?atlasGroups.get(selection[0]).get(selection[1]):[];let pageRs=chosen.slice(page*40,(page+1)*40);
 D.species.forEach((s,i)=>{let parent='cell_'+s.short;elements.push({data:{id:parent,label:names[s.short],color:colors[s.short],kind:'cell',species:s.short}});let groups=[...atlasGroups.get(s.short)];if(level===0||level===1&&s.short!==atlasFocus||active&&s.short!==selection[0]){elements.push(cyNode('summary_'+s.short,s.short+'\n'+s.reactions.length+' 反応\n'+Object.keys(s.metabolites).length+' 代謝物\n'+groups.length+' 分類',level===0?i*390:(s.short===(active?selection[0]:atlasFocus)?400:(i*390)),level===0?300:-280,colors[s.short],'summary',{parent,species:s.short}));}else if(level===1){groups.forEach(([g,rs],j)=>elements.push(cyNode('g_'+s.short+'_'+j,g+'\n'+rs.length+' 反応',(j%3)*235,100+Math.floor(j/3)*95,colors[s.short],'group',{parent,species:s.short,group:g})));}else{pageRs.forEach((r,j)=>elements.push(cyNode('ar_'+j,r.id+'\n'+r.name.slice(0,36),(j%4)*240,220+Math.floor(j/4)*100,colors[s.short],'reaction',{parent,species:s.short,reaction:r.id})));}});
 if(level===0){elements.push(cyNode('medium','共有培地\n細胞外の交換プール',390,level===0?0:-550,'#687f8b','summary'));D.species.forEach(s=>{let ex=s.reactions.filter(r=>r.exchange).length;elements.push(cyEdge('boundary_'+s.short,'medium',level===0?'summary_'+s.short:'g_'+s.short+'_0',ex+' 交換反応 · 境界一覧','mapping'))});}
 initMap(elements);mapCy.off('tap');mapCy.on('tap','node',e=>{const d=e.target.data();if(d.group){atlasDraw(2,[d.species,d.group]);return}if(d.kind==='summary'&&d.species){atlasFocus=d.species;atlasDraw(1);return}if(d.reaction){atlasReaction(d.species,d.reaction);return}if(d.id==='medium'){atlasMedium();}});
 mapCy.on('zoom',()=>{if(!atlasAuto||atlasBusy)return;let z=mapCy.zoom();$('atlasStatus').textContent=['細胞全体','全反応の分類','反応一覧'][atlasLevel]+' · '+Math.round(z*100)+'%';if(z>1.25&&atlasLevel===0){atlasDraw(1)}else if(z<.24&&atlasLevel>0){atlasDraw(atlasLevel-1)}});
 $('atlasStatus').textContent=['細胞全体','全反応の分類','反応一覧'][level]+' · '+Math.round(mapCy.zoom()*100)+'%';document.querySelector('.panelhead h2').textContent=active?selection.join(' / '):'3つの細胞と共有培地';
 $('context').innerHTML='<h2>'+ (active?esc(selection.join(' · ')):'代謝全体の階層表示')+'</h2><p>各色の囲みが独立した細胞です。全6,733反応を分類に含めています。</p><p>細胞 → 分類 → 反応 → 基質・生成物の順にクリックして展開します。「1段折りたたむ」で戻れます。</p><p>分類は元モデルのサブシステム注釈を優先し、未注釈は反応名による索引です。生化学的経路の実証や完全なKEGG分類ではありません。</p>';
 if(active){$('context').insertAdjacentHTML('beforeend','<p>'+chosen.length+' 反応中 '+(page*40+1)+'–'+Math.min((page+1)*40,chosen.length)+' を表示。全件をページ送りで参照できます。</p><button id="atlasPrev">前の40反応</button><button id="atlasNext">次の40反応</button>');$('atlasPrev').disabled=page===0;$('atlasNext').disabled=(page+1)*40>=chosen.length;$('atlasPrev').onclick=()=>atlasDraw(2,selection,page-1);$('atlasNext').onclick=()=>atlasDraw(2,selection,page+1);}
  const nav=document.createElement('div');nav.innerHTML='<label>詳しく見る細胞<select id="atlasSpecies" style="width:100%">'+D.species.map(s=>'<option value="'+s.short+'">'+names[s.short]+'</option>').join('')+'</select></label><label>反応分類<select id="atlasCategory" style="width:100%"></select></label><button id="atlasOpenCategory">この分類を展開</button>';$('context').prepend(nav);$('atlasSpecies').value=active?selection[0]:atlasFocus;const fillCategories=()=>{$('atlasCategory').innerHTML=[...atlasGroups.get($('atlasSpecies').value)].map(([g,rs])=>'<option value="'+esc(g)+'">'+esc(g)+' ('+rs.length+')</option>').join('')};fillCategories();if(active)$('atlasCategory').value=selection[1];$('atlasSpecies').onchange=()=>{atlasFocus=$('atlasSpecies').value;atlasDraw(1)};$('atlasOpenCategory').onclick=()=>atlasDraw(2,[$('atlasSpecies').value,$('atlasCategory').value]);
 atlasBusy=false;
}
function atlasReaction(short,id){let s=D.species.find(s=>s.short===short),r=s.reactions.find(r=>r.id===id);let parent='detailcell';let els=[{data:{id:parent,label:names[short]+' · 細胞内 / モデル区画は反応詳細を参照',kind:'cell',color:colors[short]}}];els.push(cyNode('selected',id,350,220,colors[short],'reaction',{parent}));let pairs=Object.entries(r.stoich);let indices=[0,0];pairs.forEach(([m,c],i)=>{let side=c<0?0:1;els.push(cyNode('met'+i,m+'\n'+s.metabolites[m].name,(side?680:0),80+indices[side]++*100,colors[short],'metabolite',{parent}));els.push(cyEdge('sto'+i,c<0?'met'+i:'selected',c<0?'selected':'met'+i,String(Math.abs(c))))});initMap(els);$('context').innerHTML='<h2>'+esc(id)+'</h2><p>'+esc(r.name)+'</p><div class="equation">'+esc(r.equation)+'</div><p>上下限: '+r.bounds.join(' ～ ')+'</p><p>GPR: '+esc(r.gpr||'未注釈')+'</p><p>矢印は化学量論の正方向。交換反応の細胞外代謝物もモデル所属で囲んでいます。</p><button id="atlasReturn">分類の反応一覧に戻る</button>';$('atlasReturn').onclick=()=>atlasDraw(2,atlasSelected,atlasPage)}
function atlasMedium(){let ids=[...new Set(D.species.flatMap(s=>s.reactions.filter(r=>r.pool).map(r=>r.pool)))].sort();$('context').innerHTML='<h2>共有培地の交換境界</h2><p>'+ids.length+' プール。選択して3種の交換上下限を比較できます。</p><select id="atlasPool" style="width:100%">'+ids.map(id=>'<option>'+esc(id)+'</option>').join('')+'</select><button id="atlasPoolOpen">境界を確認</button>';$('atlasPoolOpen').onclick=()=>showPool($('atlasPool').value)}
$('atlasHome').onclick=()=>atlasDraw(0);$('atlasGroups').onclick=()=>atlasDraw(1);$('atlasBack').onclick=()=>atlasDraw(Math.max(0,atlasLevel-1));$('atlasFit').onclick=()=>{atlasBusy=true;mapCy.fit(undefined,35);atlasBusy=false};$('atlasPlus').onclick=()=>mapCy.zoom(mapCy.zoom()*1.3);$('atlasMinus').onclick=()=>mapCy.zoom(mapCy.zoom()/1.3);$('atlasAuto').onchange=e=>atlasAuto=e.target.checked;atlasDraw(0);
// Relative zoom thresholds adapt to the fitted size of each level.
const atlasDrawBase=atlasDraw;
atlasDraw=function(level,selection=null,page=0){atlasDrawBase(level,selection,page);const base=mapCy.zoom();mapCy.off('zoom');mapCy.on('zoom',()=>{let z=mapCy.zoom();$('atlasStatus').textContent=['細胞全体','全反応の分類','反応一覧'][atlasLevel]+' · '+Math.round(z*100)+'%';if(!atlasAuto||atlasBusy)return;if(level===0&&z>base*1.65)atlasDraw(1);else if(level===1&&z>base*1.8){let ns=mapCy.nodes('[kind="group"]');let nearest=ns.sort((a,b)=>{let p=a.renderedPosition(),q=b.renderedPosition(),x=mapCy.width()/2,y=mapCy.height()/2;return Math.hypot(p.x-x,p.y-y)-Math.hypot(q.x-x,q.y-y)})[0];if(nearest)atlasDraw(2,[nearest.data('species'),nearest.data('group')]);}else if(level>0&&z<base*.65)atlasDraw(level-1)});};atlasDraw(0);
// Collapsed connections represent shared metabolites, never inferred fluxes.
const atlasDrawWithZoom=atlasDraw;
atlasDraw=function(level,selection=null,page=0){atlasDrawWithZoom(level,selection,page);if(level!==1)return;const s=D.species.find(s=>s.short===atlasFocus),groups=[...atlasGroups.get(atlasFocus)];const currency=/^(h|h2o|atp|adp|amp|pi|ppi|nad|nadh|nadp|nadph|coa|o2|co2)_[cep]$/;let sets=groups.map(([,rs])=>new Set(rs.flatMap(r=>Object.keys(r.stoich)).filter(m=>!currency.test(m))));let links=[];for(let i=0;i<sets.length;i++)for(let j=i+1;j<sets.length;j++){let shared=[...sets[i]].filter(m=>sets[j].has(m));if(shared.length)links.push(cyEdge('group_link_'+i+'_'+j,'g_'+s.short+'_'+i,'g_'+s.short+'_'+j,'','mapping',{shared:shared.join(', '),count:shared.length}))}mapCy.add(links);mapCy.on('tap','edge',e=>{let d=e.target.data();if(!d.shared)return;const p=document.createElement('p');p.textContent=d.count+' 種の共有代謝物（フラックス方向は未計算）: '+d.shared;p.style.overflowWrap='anywhere';$('context').append(p)});$('context').insertAdjacentHTML('beforeend','<p>分類間の細線は同じ代謝物を共有する構造上の接続です。水・ATP等を除外。線を選ぶと物質一覧を表示します。流量・方向は示しません。</p>');};atlasDraw(0);
