#!/usr/bin/env python3
"""DAgger-style exact relabeling of states visited by the GPU dFBA rollout.

The original dictionary is teacher-forced: its states are generated by exact
CPU trajectories.  During a long GPU rollout, small errors shift biomass and
medium concentrations, so the surrogate is queried on states absent from that
distribution.  This script executes GPU-only rollouts, captures those states,
solves the exact three-stage HiGHS problem at the same states, and appends the
resulting exact-feasible flux anchors to a new dictionary.
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor
import json
import multiprocessing as mp
from pathlib import Path
import sys

import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.augment_cooperative_surrogate_active import append_to_artifact
from scripts.benchmark_cooperative_surrogate_e2e import (
    CONSORTIUM_PROFILES, load_consortium_profile, make_environment,
)
from src.community_solver import CooperativeCommunityFbaSolver
from src.utils import load_sbml_models, select_consortium_models


def collect_gpu_contexts(
    artifact: str,
    seed: int,
    steps: int,
    candidates: int,
    rerank_pool: int,
    decision_strength: float,
    consortium_profile: str = "legacy3",
    initial_nh4: float | None = None,
    match_pha: bool = False,
    multioutput_strength: float = 0.0,
    max_iterations: int = 400,
) -> dict:
    env = make_environment(
        Path(artifact),
        steps,
        gpu_qp_projection=True,
        gpu_qp_only=True,
        gpu_qp_candidates=candidates,
        gpu_qp_rerank_pool=rerank_pool,
        gpu_qp_decision_strength=decision_strength,
        consortium_profile=consortium_profile,
        initial_nh4=initial_nh4,
        gpu_qp_match_pha=match_pha,
        gpu_qp_multioutput_strength=multioutput_strength,
        gpu_qp_max_iterations=max_iterations,
    )
    env.simulator.cooperative_capture_training_snapshot = True
    rng = np.random.default_rng(seed)
    env.reset(seed=seed)
    contexts = []
    rejected_queries = 0
    for step in range(steps):
        action = rng.uniform(0.05, 0.95, size=5).astype(np.float32)
        _, _, terminated, truncated, _ = env.step(action)
        snapshot = env.simulator._cooperative_solver.last_training_snapshot
        if snapshot is None:
            raise RuntimeError("GPU rollout did not expose a training snapshot")
        contexts.append(np.asarray(snapshot["context"], dtype=np.float32))
        rejected_queries += int(snapshot.get("source") == "gpu_rejected_query")
        if (step+1) % 30 == 0:
            print(f"collection seed={seed} step={step+1}/{steps}", flush=True)
        if terminated or truncated:
            break
    assert env.simulator._cooperative_solver.cpu_lp_stage_calls == 0
    return {"seed": int(seed), "contexts": np.stack(contexts),
            "rejected_queries": rejected_queries}


def label_exact_context_chunk(
    contexts: np.ndarray, consortium_profile: str = "legacy3",
    optimize_live_objectives: bool = True,
) -> np.ndarray:
    models = load_consortium_profile(consortium_profile)
    solver = CooperativeCommunityFbaSolver(
        models,
        coexistence_fraction=0.99,
        objective_fraction=0.99,
        maximum_coexistence_growth=0.005,
        optimize_live_objectives=optimize_live_objectives,
        parsimonious_exchange=True,
        highs_method="highs-ds",
        capture_training_snapshot=True,
    )
    species = list(models)
    shared_ids = sorted(solver._exchange_terms)
    n_fluxes = solver.n_fluxes
    expected = len(species) + len(shared_ids) + 3 * n_fluxes
    if contexts.shape[1] != expected:
        raise ValueError(
            f"GPU context width {contexts.shape[1]} does not match exact layout {expected}"
        )
    biomass_stop = len(species)
    supply_stop = biomass_stop + len(shared_ids)
    lower_stop = supply_stop + n_fluxes
    upper_stop = lower_stop + n_fluxes
    labels = []
    for context in contexts:
        biomass = {
            name: float(context[index]) for index, name in enumerate(species)
        }
        supply = context[biomass_stop:supply_stop]
        lower = context[supply_stop:lower_stop]
        upper = context[lower_stop:upper_stop]
        objective = context[upper_stop:]
        for name, (start, end) in solver._offsets.items():
            for local, reaction in enumerate(models[name].reactions):
                reaction.bounds = (
                    float(lower[start + local]),
                    float(upper[start + local]),
                )
            # Context stores the effective maximization vector, including the
            # growth/PHB/PHV switch. Replaying only bounds silently mislabels it.
            models[name].objective = {
                reaction: float(objective[start + local])
                for local, reaction in enumerate(models[name].reactions)
                if objective[start + local] != 0.0
            }
            models[name].objective.direction = "max"
        medium = {
            metabolite: max(0.0, float(value)) * 0.2
            for metabolite, value in zip(shared_ids, supply)
        }
        solver.last_training_snapshot = None
        solutions = solver.solve(models, biomass, medium, dt=0.2)
        if any(solution is None for solution in solutions.values()):
            raise RuntimeError("exact relabeling became infeasible")
        snapshot = solver.last_training_snapshot
        if snapshot is None:
            raise RuntimeError("exact solver did not capture a label")
        np.testing.assert_allclose(
            snapshot["context"], context, rtol=1e-6, atol=1e-7,
            err_msg="exact relabeling changed the GPU query's bounds/objectives/supply",
        )
        labels.append(np.asarray(snapshot["fluxes"], dtype=np.float32))
    return np.stack(labels)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("rollout_artifact", type=Path)
    parser.add_argument("base_dictionary", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--trajectories", type=int, default=3)
    parser.add_argument("--steps", type=int, default=120)
    parser.add_argument("--seed", type=int, default=20274041)
    parser.add_argument("--workers", type=int, default=3)
    parser.add_argument("--candidates", type=int, default=128)
    parser.add_argument("--rerank-pool", type=int, default=128)
    parser.add_argument("--decision-strength", type=float, default=4.0)
    parser.add_argument("--consortium", choices=CONSORTIUM_PROFILES, default="legacy3")
    parser.add_argument("--initial-nh4", type=float, default=None)
    parser.add_argument("--match-pha", action="store_true")
    parser.add_argument("--multioutput-strength", type=float, default=0.0)
    parser.add_argument("--max-iterations", type=int, default=400)
    parser.add_argument("--report", type=Path, default=None)
    args = parser.parse_args()

    seeds = [args.seed + 1009 * index for index in range(args.trajectories)]
    if set(seeds) & set(range(20286001, 20286006)):
        raise ValueError("reserved final qualification seeds cannot become training data")
    rollouts = [
        collect_gpu_contexts(
            str(args.rollout_artifact),
            seed,
            args.steps,
            args.candidates,
            args.rerank_pool,
            args.decision_strength,
            args.consortium,
            args.initial_nh4,
            args.match_pha,
            args.multioutput_strength,
            args.max_iterations,
        )
        for seed in seeds
    ]
    contexts = np.concatenate([item["contexts"] for item in rollouts])
    row_seeds = np.concatenate([np.full(len(item["contexts"]), item["seed"]) for item in rollouts])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(args.output.with_suffix(".queries.npz"), contexts=contexts, seeds=row_seeds)
    chunks = [chunk for chunk in np.array_split(contexts, args.workers) if len(chunk)]
    if len(chunks) == 1:
        labels = label_exact_context_chunk(chunks[0], args.consortium)
    else:
        with ProcessPoolExecutor(
            max_workers=len(chunks), mp_context=mp.get_context("spawn")
        ) as executor:
            labels = np.concatenate(list(executor.map(
                label_exact_context_chunk, chunks, [args.consortium] * len(chunks)
            )))
    np.savez_compressed(args.output.with_suffix(".labels.npz"), contexts=contexts,
                        fluxes=labels, seeds=row_seeds)
    report = append_to_artifact(
        args.base_dictionary,
        args.output,
        contexts,
        labels,
        {
            "method": "DAgger_GPU_state_exact_HiGHS_relabel",
            "available_rows": int(len(contexts)),
            "selected_rows": int(len(contexts)),
        },
        seeds,
    )
    report.update(
        {
            "rollout_artifact": str(args.rollout_artifact),
            "rollout_candidates": int(args.candidates),
            "rollout_rerank_pool": int(args.rerank_pool),
            "rollout_decision_strength": float(args.decision_strength),
            "rollout_multioutput_strength":args.multioutput_strength,
            "rollout_max_iterations":args.max_iterations,
            "steps": int(args.steps),
            "consortium_profile": args.consortium,
            "initial_nh4_mM": args.initial_nh4,
            "optimize_live_objectives": True,
            "gpu_rejected_queries": sum(item["rejected_queries"] for item in rollouts),
        }
    )
    report_path = args.report or args.output.with_suffix(".dagger.json")
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
