const fs=require('fs'),vm=require('vm'),assert=require('assert');
const runtime=fs.readFileSync(__dirname+'/../web/js/runtime.js','utf8');
const flow=fs.readFileSync(__dirname+'/../web/js/flow.js','utf8');
const code=runtime.slice(0,runtime.indexOf('let flowRendering='))+flow.slice(flow.indexOf('function lineConflict('),flow.indexOf('function separateSideCompounds('));
const sandbox={};vm.createContext(sandbox);vm.runInContext(code+';this.Index=FlowSpatialIndex;this.conflict=lineConflict',sandbox);
const index=new sandbox.Index(180,20);
const paths=Array.from({length:100},(_,i)=>Array.from({length:17},(_,j)=>({x:(i%10)*250+j*9,y:Math.floor(i/10)*230+Math.sin(j/16*Math.PI)*60})));
paths.forEach(p=>index.add(p));let exhaustive=0,indexed=0;
const candidates=paths.flatMap(line=>Array.from({length:27},(_,i)=>line.map(p=>({x:p.x+30,y:p.y+i*2}))));
const t0=performance.now();const globalScores=candidates.map(c=>paths.reduce((sum,p)=>{exhaustive++;return sum+sandbox.conflict(c,p)},0));const t1=performance.now();
const localScores=candidates.map(c=>index.near(c).reduce((sum,p)=>{indexed++;return sum+sandbox.conflict(c,p)},0));const t2=performance.now();
assert.deepEqual(localScores,globalScores);assert(indexed<exhaustive/5);
console.log(JSON.stringify({test:'100-reaction spatial collision parity',globalComparisons:exhaustive,indexedComparisons:indexed,globalMs:Math.round(t1-t0),indexedMs:Math.round(t2-t1)}));
const D={model_fingerprint:'model-a',medium:{a_e:1},species:[{short:'test',reactions:[{id:'R',pool:'a_e'}],metabolites:{a_c:{}}}]};
const st={s:D.species[0],pool:'a_e',selected:'r_R_1',nodes:new Map([['r_R_1',{data:{id:'r_R_1',reaction:'R'},position:{x:10,y:20}}]]),edges:[],keep:new Set(['r_R_1']),hiddenReactions:new Set(['r_R_1']),omissionGroups:new Map([['m_a_c:before',new Set(['r_R_1'])]]),mediumOverride:{a_e:.2},mediumDraft:{a_e:.3},majorShown:new Map(),majorPending:new Map()};
const empty={length:0};const context={D,flowState:st,autoMajorEnabled:true,mapCy:{nodes:()=>({map:()=>[]}),getElementById:()=>empty,zoom:()=>.8,pan:()=>({x:4,y:5})},console};vm.createContext(context);
vm.runInContext(runtime.slice(runtime.indexOf('const snapshotSets='),runtime.indexOf('async function restoreAtlasSession('))+';this.pack=packAtlasSession;this.validate=validateAtlasSession;',context);
const payload=context.pack();assert.equal(payload.view.mediumRoots[0],'a_e');assert.equal(payload.view.mediumDraft.a_e,.3);assert.equal(payload.view.hiddenReactions[0],'r_R_1');context.validate(payload);
assert.throws(()=>context.validate({...payload,model:'model-b'}));assert.throws(()=>context.validate({...payload,view:{...payload.view,mediumOverride:{a_e:-1}}}));
assert.throws(()=>context.validate({...payload,view:{...payload.view,nodes:[{data:{id:'bad',reaction:'not_in_model'},position:{x:1,y:1}}]}}));
console.log('PASS session selection, omission, draft, roots, positions and validation');
