"""Gene identifier reconciliation for the three-member consortium.

The project uses strain-specific INSDC/NCBI locus tags inside GPR rules.  A
globally unique project identifier (``CCG_<organism>_<locus_tag>``) and all
legacy model/FASTA/protein identifiers are maintained in sidecar registry
files.  This keeps SBML GPRs readable without pretending that a gene symbol or
protein accession is a universal gene identifier.
"""

from __future__ import annotations

import json
import csv
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Mapping

from cobra.core.gene import GPR
from cobra.manipulation import rename_genes
from cobra.manipulation.delete import remove_genes
from sympy.logic import simplify_logic


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = ROOT / "config/gene_id_registry.json"
DEFAULT_ALIAS_TABLE = ROOT / "models/gene_registry/gene_id_aliases.tsv"
NON_BIOLOGICAL_GENE_IDS = {"spontaneous"}
NON_RESOLVABLE_ALIAS_TYPES = {
    "gene_symbol",
    "model_gene_name",
    "quarantined_legacy_id",
}


@dataclass(frozen=True)
class FastaGene:
    raw_id: str
    model_safe_id: str
    locus_tag: str
    protein_accession: str
    product: str
    gene_symbol: str = ""


@dataclass
class GeneRegistryRecord:
    project_gene_id: str
    organism_key: str
    species_name: str
    assembly_accession: str
    canonical_locus_tag: str
    canonical_model_gene_id: str
    protein_accession: str = ""
    gene_symbol: str = ""
    product: str = ""
    mapping_status: str = "mapped"
    mapping_method: str = ""
    evidence: str = ""
    reaction_ids: set[str] = field(default_factory=set)
    aliases: dict[str, str] = field(default_factory=dict)

    def add_alias(self, identifier: str, alias_type: str) -> None:
        if identifier:
            self.aliases.setdefault(identifier, alias_type)

    def as_tsv_row(self) -> dict[str, Any]:
        return {
            "project_gene_id": self.project_gene_id,
            "organism_key": self.organism_key,
            "species_name": self.species_name,
            "assembly_accession": self.assembly_accession,
            "canonical_locus_tag": self.canonical_locus_tag,
            "canonical_model_gene_id": self.canonical_model_gene_id,
            "protein_accession": self.protein_accession,
            "gene_symbol": self.gene_symbol,
            "product": self.product,
            "mapping_status": self.mapping_status,
            "mapping_method": self.mapping_method,
            "reaction_count": len(self.reaction_ids),
            "reaction_ids": ";".join(sorted(self.reaction_ids)),
            "evidence": self.evidence,
        }


def load_registry_config(path: Path = DEFAULT_CONFIG) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if payload.get("schema_version") != 1:
        raise ValueError(f"Unsupported gene registry schema: {payload.get('schema_version')}")
    return payload


def profile_by_key(config: Mapping[str, Any], organism_key: str) -> Mapping[str, Any]:
    for profile in config["organisms"]:
        if profile["organism_key"] == organism_key:
            return profile
    raise KeyError(f"Unknown organism key: {organism_key}")


def model_safe_identifier(identifier: str) -> str:
    """Return the identifier form generated by COBRApy's SBML escaping."""

    safe = re.sub(r"[^A-Za-z0-9_]", "_", identifier)
    return safe if not safe[:1].isdigit() else f"G_{safe}"


def project_gene_id(organism_key: str, locus_tag: str) -> str:
    return f"CCG_{model_safe_identifier(organism_key)}_{model_safe_identifier(locus_tag)}"


def _header_value(header: str, key: str) -> str:
    match = re.search(rf"\[{re.escape(key)}=([^\]]+)\]", header)
    return match.group(1).strip() if match else ""


def parse_fasta_gene_headers(path: Path) -> list[FastaGene]:
    records: list[FastaGene] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.startswith(">"):
                continue
            header = line[1:].rstrip("\n")
            raw_id = header.split(maxsplit=1)[0]
            locus_tag = _header_value(header, "locus_tag")
            if not locus_tag:
                continue
            records.append(
                FastaGene(
                    raw_id=raw_id,
                    model_safe_id=model_safe_identifier(raw_id),
                    locus_tag=locus_tag,
                    protein_accession=_header_value(header, "protein_id"),
                    product=_header_value(header, "protein"),
                    gene_symbol=_header_value(header, "gene"),
                )
            )
    return records


def _fasta_indexes(
    profile: Mapping[str, Any], root: Path
) -> tuple[dict[str, FastaGene], dict[str, FastaGene]]:
    relative = profile.get("fasta_file")
    if not relative:
        return {}, {}
    records = parse_fasta_gene_headers(root / relative)
    by_alias: dict[str, FastaGene] = {}
    by_locus: dict[str, FastaGene] = {}
    for record in records:
        by_locus[record.locus_tag] = record
        for alias in (record.raw_id, record.model_safe_id, record.protein_accession):
            if alias:
                by_alias[alias] = record
    return by_alias, by_locus


def build_model_registry(
    model,
    profile: Mapping[str, Any],
    *,
    root: Path = ROOT,
) -> tuple[list[GeneRegistryRecord], dict[str, str]]:
    """Build records and an old-ID to locus-tag rename map for one model."""

    organism_key = profile["organism_key"]
    species_name = profile["species_name"]
    assembly = profile["assembly_accession"]
    locus_pattern = re.compile(profile["locus_tag_pattern"])
    manual = profile.get("manual_aliases", {})
    unresolved = profile.get("unresolved_ids", {})
    fasta_alias, fasta_locus = _fasta_indexes(profile, root)
    records: dict[str, GeneRegistryRecord] = {}
    rename_map: dict[str, str] = {}

    for gene in model.genes:
        old_id = gene.id
        method = ""
        evidence = ""
        fasta = None
        locus_tag = ""
        status = "mapped"

        if old_id in NON_BIOLOGICAL_GENE_IDS:
            status = "special"
        elif old_id in unresolved:
            status = "unresolved"
            evidence = unresolved[old_id]
        elif old_id in manual:
            locus_tag = manual[old_id]["canonical_locus_tag"]
            evidence = manual[old_id]["evidence"]
            method = "manual_evidence"
        elif locus_pattern.fullmatch(old_id):
            locus_tag = old_id
            method = "native_locus_tag"
        elif old_id in fasta_alias:
            fasta = fasta_alias[old_id]
            locus_tag = fasta.locus_tag
            method = "genome_fasta_header"
        else:
            status = "unresolved"
            evidence = "No unambiguous locus-tag mapping was found."

        if locus_tag and fasta is None:
            fasta = fasta_locus.get(locus_tag)

        if status == "mapped":
            key = project_gene_id(organism_key, locus_tag)
            canonical_model_id = locus_tag
        else:
            key = f"CCG_{status.upper()}_{model_safe_identifier(organism_key)}_{model_safe_identifier(old_id)}"
            canonical_model_id = old_id

        record = records.get(key)
        if record is None:
            record = GeneRegistryRecord(
                project_gene_id=key,
                organism_key=organism_key,
                species_name=species_name,
                assembly_accession=assembly,
                canonical_locus_tag=locus_tag,
                canonical_model_gene_id=canonical_model_id,
                protein_accession=fasta.protein_accession if fasta else "",
                gene_symbol=fasta.gene_symbol if fasta else "",
                product=fasta.product if fasta else "",
                mapping_status=status,
                mapping_method=method,
                evidence=evidence,
            )
            records[key] = record
        elif record.mapping_status != status:
            raise ValueError(f"Conflicting mappings for {key}")

        record.reaction_ids.update(reaction.id for reaction in gene.reactions)
        record.add_alias(old_id, "model_gene_id")
        if gene.name and gene.name not in {old_id, f"G_{old_id}"}:
            record.add_alias(gene.name, "model_gene_name")
        if locus_tag:
            record.add_alias(locus_tag, "locus_tag")
        if fasta:
            record.add_alias(fasta.raw_id, "fasta_id")
            record.add_alias(fasta.model_safe_id, "legacy_sbml_gene_id")
            record.add_alias(fasta.protein_accession, "ncbi_protein")
            record.add_alias(fasta.gene_symbol, "gene_symbol")
        if status == "mapped" and old_id != locus_tag:
            rename_map[old_id] = locus_tag

    # Preserve configured legacy aliases after the model has already been
    # canonicalized, so rebuilding the registry never loses provenance.
    for alias, mapping in manual.items():
        locus_tag = mapping["canonical_locus_tag"]
        key = project_gene_id(organism_key, locus_tag)
        if key in records:
            records[key].add_alias(alias, "manual_legacy_alias")

    # Keep retired/ambiguous source IDs in the audit trail even after Boolean
    # simplification has removed them from the production GPR graph.
    present_aliases = {alias for record in records.values() for alias in record.aliases}
    for alias, evidence in unresolved.items():
        if alias in present_aliases:
            continue
        key = (
            f"CCG_RETIRED_{model_safe_identifier(organism_key)}_"
            f"{model_safe_identifier(alias)}"
        )
        record = GeneRegistryRecord(
            project_gene_id=key,
            organism_key=organism_key,
            species_name=species_name,
            assembly_accession=assembly,
            canonical_locus_tag="",
            canonical_model_gene_id=alias,
            mapping_status="retired_unresolved",
            mapping_method="boolean_equivalent_retirement",
            evidence=evidence,
        )
        record.add_alias(alias, "quarantined_legacy_id")
        records[key] = record

    return sorted(records.values(), key=lambda item: item.project_gene_id), rename_map


def canonicalize_model_gene_ids(
    model,
    profile: Mapping[str, Any],
    *,
    root: Path = ROOT,
) -> dict[str, Any]:
    """Rename mapped GPR genes to locus tags and attach registry metadata."""

    records, rename_map = build_model_registry(model, profile, root=root)
    before = len(model.genes)
    duplicate_targets = {
        new_id
        for old_id, new_id in rename_map.items()
        if new_id in model.genes and old_id != new_id
    }
    simplify_reaction_ids: set[str] = set()
    for old_id, new_id in rename_map.items():
        if new_id not in duplicate_targets:
            continue
        for identifier in (old_id, new_id):
            if identifier in model.genes:
                simplify_reaction_ids.update(
                    reaction.id for reaction in model.genes.get_by_id(identifier).reactions
                )
    for record in records:
        if (
            record.mapping_status == "unresolved"
            and record.canonical_model_gene_id in model.genes
        ):
            simplify_reaction_ids.update(
                reaction.id
                for reaction in model.genes.get_by_id(
                    record.canonical_model_gene_id
                ).reactions
            )
    rename_genes(model, rename_map)
    simplified_gprs = 0
    for reaction_id in sorted(simplify_reaction_ids):
        reaction = model.reactions.get_by_id(reaction_id)
        if not reaction.gene_reaction_rule:
            continue
        simplified = GPR.from_symbolic(
            simplify_logic(reaction.gpr.as_symbolic(), force=True)
        ).to_string()
        if simplified != reaction.gene_reaction_rule:
            reaction.gene_reaction_rule = simplified
            simplified_gprs += 1

    # Only retire explicitly quarantined identifiers that became unused as a
    # consequence of Boolean-equivalent simplification.  Other orphan genes
    # may be meaningful genome annotations and are preserved.
    retired_unresolved = []
    for record in records:
        identifier = record.canonical_model_gene_id
        if (
            record.mapping_status == "unresolved"
            and identifier in model.genes
            and not model.genes.get_by_id(identifier).reactions
        ):
            remove_genes(
                model, [model.genes.get_by_id(identifier)], remove_reactions=False
            )
            retired_unresolved.append(identifier)
    by_locus = {
        record.canonical_locus_tag: record
        for record in records
        if record.mapping_status == "mapped"
    }
    for gene in model.genes:
        record = by_locus.get(gene.id)
        if record is None:
            continue
        gene.notes["project_gene_id"] = record.project_gene_id
        gene.notes["canonical_locus_tag"] = record.canonical_locus_tag
        gene.notes["assembly_accession"] = record.assembly_accession
        if record.protein_accession:
            gene.annotation["ncbiprotein"] = record.protein_accession
        if record.gene_symbol:
            gene.notes["gene_symbol"] = record.gene_symbol

    model.repair()
    remaining_unresolved = sorted(
        record.canonical_model_gene_id
        for record in records
        if record.mapping_status == "unresolved"
        and record.canonical_model_gene_id in model.genes
    )
    historical_quarantined = sorted(
        record.canonical_model_gene_id
        for record in records
        if record.mapping_status == "retired_unresolved"
    )
    return {
        "organism_key": profile["organism_key"],
        "genes_before": before,
        "genes_after": len(model.genes),
        "renamed_aliases": len(rename_map),
        "merged_duplicate_gene_objects": before - len(model.genes) - len(retired_unresolved),
        "simplified_gpr_rules": simplified_gprs,
        "retired_unresolved_gene_ids": sorted(retired_unresolved),
        "historical_quarantined_gene_ids": historical_quarantined,
        "unresolved_gene_ids": remaining_unresolved,
    }


def registry_alias_index(
    records: Iterable[GeneRegistryRecord],
) -> dict[tuple[str, str], str]:
    """Create an organism-scoped alias index and reject ambiguous aliases."""

    index: dict[tuple[str, str], str] = {}
    for record in records:
        for alias, alias_type in record.aliases.items():
            # Gene symbols such as fusA are functional labels and may validly
            # occur at several loci.  Keep them searchable in the TSV, but do
            # not accept them as identifiers for programmatic resolution.
            if alias_type in NON_RESOLVABLE_ALIAS_TYPES:
                continue
            key = (record.organism_key, alias)
            previous = index.get(key)
            if previous is not None and previous != record.project_gene_id:
                raise ValueError(
                    f"Ambiguous gene alias {alias!r} in {record.organism_key}: "
                    f"{previous} vs {record.project_gene_id}"
                )
            index[key] = record.project_gene_id
    return index


def load_alias_index(path: Path = DEFAULT_ALIAS_TABLE) -> dict[tuple[str, str], str]:
    """Load the generated organism-scoped resolver table."""

    index: dict[tuple[str, str], str] = {}
    with path.open(encoding="utf-8") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            if row["resolvable"].lower() not in {"true", "1", "yes"}:
                continue
            key = (row["organism_key"], row["alias"])
            project_id = row["project_gene_id"]
            previous = index.get(key)
            if previous is not None and previous != project_id:
                raise ValueError(
                    f"Ambiguous resolvable alias {key}: {previous} vs {project_id}"
                )
            index[key] = project_id
    return index


def resolve_gene_id(
    organism_key: str,
    identifier: str,
    *,
    alias_table: Path = DEFAULT_ALIAS_TABLE,
) -> str:
    """Resolve any stable/legacy alias to a globally unique project gene ID."""

    index = load_alias_index(alias_table)
    try:
        return index[(organism_key, identifier)]
    except KeyError as exc:
        raise KeyError(
            f"Unknown or non-unique gene identifier {identifier!r} for {organism_key}"
        ) from exc


def validate_canonical_gene_ids(species_name: str, model) -> None:
    """Fail fast when a production consortium model reintroduces legacy IDs."""

    if "OR16" in species_name:
        pattern = re.compile(r"^ACTI_[0-9]+$")
    elif "NS21" in species_name:
        pattern = re.compile(r"^A4W93_[0-9]+$")
    elif "Lactobacillus_plantarum" in species_name or "Lactiplantibacillus_plantarum" in species_name:
        pattern = re.compile(r"^(lp_[0-9]+|pWCFS[0-9]+_[0-9]+)$")
    else:
        return
    invalid = sorted(
        gene.id
        for gene in model.genes
        if gene.id not in NON_BIOLOGICAL_GENE_IDS and pattern.fullmatch(gene.id) is None
    )
    if invalid:
        preview = ", ".join(invalid[:5])
        raise ValueError(
            f"Non-canonical gene IDs in {species_name}: {preview}. "
            "Run scripts/model_ops/build_gene_id_registry.py --canonicalize-models."
        )
